export { gsap, ScrollTrigger, SplitText, useGSAP } from './gsap'
export { Reveal } from './Reveal'
export { useLenis } from './lenisContext'
export { SmoothScroll } from './SmoothScroll'
export { SplitReveal } from './SplitReveal'
export type { RevealTag } from './types'
export { prefersReducedMotion, useReducedMotion } from './useReducedMotion'
